services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-server
  fastapi_app:
    environment:
      REDIS_HOST: redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
    container_name: fastapi_app
    command: bash -c "bash prestart.sh && uvicorn app:app --host=0.0.0.0 --port=8000"
